/* CareOS gui/font.h -- font data model and registry.
 * Glyph tables are generated by tools/gen-font.py and committed. */
#ifndef CAREOS_FONT_H
#define CAREOS_FONT_H

#include "kernel.h"

#define FONT_FIRST_CH 32
#define FONT_LAST_CH  126
#define FONT_GLYPHS   95
#define FONT_FACES    5   /* one per font_size_t */

typedef struct {
    u8  w, h;
    i8  bearing_x;
    i8  bearing_y;
    u32 offset;
} glyph_t;

typedef struct {
    u8             px;
    u8             advance;    /* nominal cell width (monospace, or a fallback) */
    u8             line_h;
    u8             baseline;
    const glyph_t *glyphs;
    const u8      *coverage;
    /* Per-glyph horizontal advance for proportional faces, indexed the same as
     * glyphs[] (char - FONT_FIRST_CH). NULL for monospace faces, in which case
     * every glyph uses `advance` and rendering is byte-for-byte unchanged. */
    const u8      *advances;
} font_face_t;

typedef struct {
    const char        *name;
    const font_face_t  faces[FONT_FACES];
} font_family_t;

/* font_size_t lives in gui.h; forward-declare the enum tag usage via u32 to
 * avoid a circular include. Callers pass font_size_t values directly. */
void               font_init(void);
u32                font_registry_count(void);
const char        *font_registry_name(u32 index);
void               font_set_family(u32 index);
u32                font_active_index(void);
const font_face_t *font_face_at(u32 size_index);
const font_face_t *font_bold_face_at(u32 size_index);

#endif /* CAREOS_FONT_H */
