---
efiBootloaderId:      "CareOS"
installEFIFallback:   false
grubInstall:          "grub-install"
grubMkconfig:         "grub-mkconfig"
grubCfg:              "/boot/grub/grub.cfg"
grubProbe:            "grub-probe"
grubTimeout:          "10"
grubSequence:
    - "grub-install"
    - "grub-mkconfig"
