---
efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: "512MiB"
efiSystemPartitionName: "EFI System Partition"

userSwapChoices:
    - none
    - small
    - suspend
    - file

ensureSuspendToDisk: true
neverCreateSwapPartition: false
