---
userShell:        /bin/bash
defaultGroups:
    - audio
    - video
    - network
    - storage
    - optical
    - wheel
    - lp
    - rfkill
    - input

setRootPassword:  true
sudoersGroup:     wheel
doAutoLogin:      false
