---
showSupportUrl:        false
showKnownIssuesUrl:    false
showReleaseNotesUrl:   false
showDonateUrl:         false

requirements:
    requiredStorage:    10
    requiredRam:        2.0
    internetCheckUrl:   "https://example.com"
    check:
        - storage
        - ram
        - power
    nocheck:
        - internet
        - root
