#!/usr/bin/env python3
"""Rasterize a TTF into CareOS C glyph tables.

Run once on the dev machine and commit the output, exactly like
tools/gen-sounds.py. The kernel build never invokes this script.

Usage:
  python3 tools/gen-font.py fonts/JetBrainsMono-Regular.ttf \
      --name "JetBrains Mono" --symbol jetbrains_mono \
      --sizes 11,13,16,20,28 --out gui/fonts/font_jetbrains_mono.c
"""
import argparse
import sys
from dataclasses import dataclass, field
from typing import List

import freetype

FIRST_CH, LAST_CH = 32, 126
GLYPH_COUNT = LAST_CH - FIRST_CH + 1  # 95


@dataclass
class Glyph:
    w: int
    h: int
    bearing_x: int
    bearing_y: int
    offset: int


@dataclass
class Face:
    px: int
    advance: int
    line_h: int
    baseline: int
    glyphs: List[Glyph] = field(default_factory=list)
    coverage: bytearray = field(default_factory=bytearray)
    advances: List[int] = field(default_factory=list)   # per-glyph, proportional


def build_face(ttf_path: str, px: int) -> Face:
    face = freetype.Face(ttf_path)
    face.set_pixel_sizes(0, px)

    baseline = face.size.ascender >> 6
    line_h = face.size.height >> 6
    if line_h <= 0:
        line_h = baseline - (face.size.descender >> 6)

    glyphs: List[Glyph] = []
    coverage = bytearray()
    adv_list: List[int] = []

    for code in range(FIRST_CH, LAST_CH + 1):
        face.load_char(chr(code), freetype.FT_LOAD_RENDER)
        slot = face.glyph
        bmp = slot.bitmap
        adv_list.append(max(0, min(255, slot.advance.x >> 6)))

        w, h, pitch = bmp.width, bmp.rows, bmp.pitch
        offset = len(coverage)
        # bitmap.buffer is padded to `pitch` per row; copy the live columns only.
        for row in range(h):
            base = row * pitch
            coverage.extend(bmp.buffer[base:base + w])

        glyphs.append(Glyph(w, h, slot.bitmap_left, slot.bitmap_top, offset))

    # Both monospace and proportional faces are supported. The nominal cell
    # width (used where a single number is wanted, e.g. GFX_FONT_W) is the space
    # advance; the per-glyph list is emitted only when the face is proportional.
    if len(set(adv_list)) != 1:
        print(f"note: {ttf_path} at {px}px is proportional "
              f"(advances {min(adv_list)}..{max(adv_list)})")
    nominal = adv_list[ord(' ') - FIRST_CH]
    if nominal <= 0:
        nominal = max(adv_list)

    return Face(px=px, advance=nominal, line_h=line_h,
                baseline=baseline, glyphs=glyphs, coverage=coverage,
                advances=adv_list)


def _fits_u8(name, value):
    if not (0 <= value <= 255):
        sys.exit(f"error: {name}={value} does not fit in u8")


def _fits_i8(name, value):
    if not (-128 <= value <= 127):
        sys.exit(f"error: {name}={value} does not fit in i8")


def _fits_u32(name, value):
    if not (0 <= value <= 0xFFFFFFFF):
        sys.exit(f"error: {name}={value} does not fit in u32")


def emit_c(name: str, symbol: str, faces: List[Face], out_path: str, src_note: str) -> None:
    lines = []
    a = lines.append
    a("/* GENERATED by tools/gen-font.py -- do not edit by hand.")
    a(f" * Typeface: {name}")
    a(f" * Source:   {src_note}")
    a(" * JetBrains Mono is licensed under the SIL Open Font License 1.1.")
    a(" * See fonts/OFL.txt. */")
    a('#include "kernel.h"')
    a('#include "font.h"')
    a("")

    for f in faces:
        _fits_u8("px", f.px)
        _fits_u8("advance", f.advance)
        _fits_u8("line_h", f.line_h)
        _fits_u8("baseline", f.baseline)

        a(f"static const u8 {symbol}_cov_{f.px}[] = {{")
        blob = bytes(f.coverage)
        for i in range(0, len(blob), 24):
            a("    " + ",".join(str(b) for b in blob[i:i + 24]) + ",")
        a("};")
        a("")
        a(f"static const glyph_t {symbol}_glyphs_{f.px}[{GLYPH_COUNT}] = {{")
        for g in f.glyphs:
            _fits_u8("glyph.w", g.w)
            _fits_u8("glyph.h", g.h)
            _fits_i8("glyph.bearing_x", g.bearing_x)
            _fits_i8("glyph.bearing_y", g.bearing_y)
            _fits_u32("glyph.offset", g.offset)
            a(f"    {{ {g.w},{g.h},{g.bearing_x},{g.bearing_y},{g.offset} }},")
        a("};")
        a("")
        # Proportional faces carry a per-glyph advance table; monospace faces
        # omit it (the face's single `advance` covers every glyph) so their
        # output stays byte-for-byte identical to before.
        if len(set(f.advances)) > 1:
            for v in f.advances:
                _fits_u8("advance", v)
            a(f"static const u8 {symbol}_adv_{f.px}[{GLYPH_COUNT}] = {{")
            a("    " + ",".join(str(v) for v in f.advances) + ",")
            a("};")
            a("")

    a(f"const font_family_t font_{symbol} = {{")
    a(f'    .name = "{name}",')
    a("    .faces = {")
    for f in faces:
        adv = f", .advances={symbol}_adv_{f.px}" if len(set(f.advances)) > 1 else ""
        a(f"        {{ .px={f.px}, .advance={f.advance}, .line_h={f.line_h}, "
          f".baseline={f.baseline}, .glyphs={symbol}_glyphs_{f.px}, "
          f".coverage={symbol}_cov_{f.px}{adv} }},")
    a("    },")
    a("};")
    a("")

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines))


def write_preview(ttf_path: str, faces: List[Face], png_path: str) -> None:
    """Dump a glyph sheet so output can be eyeballed before rebuilding."""
    from PIL import Image  # optional; only needed for --preview
    pad = 4
    width = max(f.advance for f in faces) * 32 + pad * 2
    height = sum(f.line_h * 3 + pad for f in faces) + pad
    img = Image.new("L", (width, height), 0)
    y = pad
    for f in faces:
        for i, g in enumerate(f.glyphs):
            col, row = i % 32, i // 32
            ox = pad + col * f.advance + g.bearing_x
            oy = y + row * f.line_h + (f.baseline - g.bearing_y)
            for gy in range(g.h):
                for gx in range(g.w):
                    v = f.coverage[g.offset + gy * g.w + gx]
                    px, py = ox + gx, oy + gy
                    if 0 <= px < width and 0 <= py < height:
                        img.putpixel((px, py), v)
        y += f.line_h * 3 + pad
    img.save(png_path)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("ttf")
    p.add_argument("--name", required=True)
    p.add_argument("--symbol", required=True)
    p.add_argument("--sizes", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--preview")
    args = p.parse_args()

    sizes = [int(s) for s in args.sizes.split(",")]
    if len(sizes) != 5:
        sys.exit("error: --sizes must list exactly 5 sizes, one per font_size_t "
                 "(CAPTION,BODY,H3,H2,H1)")
    if any(sizes[i] >= sizes[i + 1] for i in range(len(sizes) - 1)):
        sys.exit("error: --sizes must be strictly ascending, smallest (CAPTION) "
                 f"to largest (H1); got {args.sizes}")

    faces = [build_face(args.ttf, px) for px in sizes]
    emit_c(args.name, args.symbol, faces, args.out, args.ttf)
    total = sum(len(f.coverage) for f in faces)
    print(f"{args.out}: 5 faces, {total} coverage bytes")

    if args.preview:
        write_preview(args.ttf, faces, args.preview)
        print(f"{args.preview}: preview written")


if __name__ == "__main__":
    main()
